postgresql:
    adapter: postgresql
    database: kusuri_gem_test
    username: kusuri_gem_test
    password: QIe2aCON4GQ8yI4awtctRjeok7NWGTtB
    encoding: utf8
    pool: 1
    timeout: 5000
    min_messages: WARNING

# mysql:
#     adapter: mysql
#     database: kusuri_gem_test
#     username: kusuri_gem_test
#     password: QIe2aCON4GQ8yI4awtctRjeok7NWGTtB
#     encoding: utf8
#     pool: 1
#     timeout: 5000
#     min_messages: WARNING
